### ISSUE TITLE
请求更新适配最新版

### ISSUE THREAD

**Issue by ZerOri** [zjns/PureNeteaseCloudMusic-Xposed#21]
RT，网易云8.0版本后此插件已不再能用，请求更新

**Comment by zjns** [comment]
> RT，网易云8.0版本后此插件已不再能用，请求更新

此项目已不再维护，请考虑购买会员。

**Comment by ZerOri** [comment]
> > RT，网易云8.0版本后此插件已不再能用，请求更新
> 
> 此项目已不再维护，请考虑购买会员。

啊这，那叨扰了，已是会员但仍然有很多想精简的地方。
