### ISSUE TITLE
Video Ad On Comment Area

### ISSUE THREAD

**Issue by auntlucy** [zjns/PureNeteaseCloudMusic-Xposed#3]
PureNeteaseCloudMusic v2.5
Netease Cloud Music v5.5.2

Video ad on comment area still keep showing. I've ticked every option and rebooted the device but it doesn't seem working. Beside that everything works fine. Thanks for making this great tool.

**Comment by zjns** [comment]
![-fb62330cdc0a17f](https://user-images.githubusercontent.com/10793522/45731646-3387cc80-bc0b-11e8-96e9-b50634d9ff41.jpg)
Is it?

**Comment by xiuluo** [comment]
> ![-fb62330cdc0a17f](https://user-images.githubusercontent.com/10793522/45731646-3387cc80-bc0b-11e8-96e9-b50634d9ff41.jpg)
> Is it?

他说的应该是歌曲评论区里的广告。
![screenshot_ _20180922-174642](https://user-images.githubusercontent.com/2190708/45915895-ba4cdb80-be8f-11e8-88a4-68c191aa485f.png)

**Comment by zjns** [comment]
@auntlucy It should be fixed with version 2.5.2.

**Comment by auntlucy** [comment]
Nice work! Good to know.

**Comment by auntlucy** [comment]
Looks like the video ads are back again. Could you please take a look?
